# Generated by Django 5.1.7 on 2025-03-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='drop_location',
            field=models.CharField(max_length=255),
        ),
    ]
