# Generated by Django 5.1.7 on 2025-03-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride_app', '0002_alter_ride_drop_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverprofile',
            old_name='driver',
            new_name='user',
        ),
    ]
